spring:
  application:
    name: eCommerce
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:h2:mem:eCommerceDb
    driverClassName: org.h2.Driver
    databasePlatform: org.hibernate.dialect.H2Dialect
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
