spring:
  application:
    name: eCommerce
  jpa:
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:eCommerceDb
    driverClassName: org.h2.Driver
    databasePlatform: org.hibernate.dialect.H2Dialect
